### ISSUE TITLE
Double slash in image names

### ISSUE THREAD

**Issue by brokenpylons** [UM-LPM/short-courses#1]
For example `https://pmd.lpm.feri.um.si/assets/img/256//MNCV.jpeg`.

**Comment by cecepasinechka** [comment]
Fixed issue. Changed code line ``` <img src="{{ site.baseurl }}/assets/img/{256, 512, 1024}/{{ post.id }}.jpeg" ``` to ``` <img src="{{ site.baseurl }}/assets/img/{256, 512, 1024}{{ post.id }}.jpeg" ``` as it automatically added one ``` / ``` .
