### ISSUE TITLE
Wrong urls on search (some get č, š, ž)!

### ISSUE THREAD

**Issue by Mir1001** [UM-LPM/short-courses#3]
## Example
1. Select search and write "obdelava"
<img width="1413" alt="image" src="https://github.com/UM-LPM/short-courses/assets/623148/fbec860b-3e3a-4761-a833-0b921bd28d5a">
2. If you click on the first course, you are redirected to: 

>  https://pmd.lpm.feri.um.si/UŠU
>   instead of:
>   https://pmd.lpm.feri.um.si/USU

<img width="1412" alt="image" src="https://github.com/UM-LPM/short-courses/assets/623148/4834f25f-2e6d-4259-9819-ad6b4e1518e7">

**Comment by cecepasinechka** [comment]
Fixed issue. Problem with search.json that got rid of all the special characters. Solved by unfiltered search.json (now renamed to course-data.json) and conversion done in the script.
