### ISSUE TITLE
Sort courses by date

### ISSUE THREAD

**Issue by brokenpylons** [UM-LPM/short-courses#49]
The courses are currently shuffled on every reload. Can we sort them by date?

**Comment by cecepasinechka** [comment]
The current script checks if the each course has `executionStartDate`. The ones that have that data are sorted based on closest upcoming course. For the others a seed is generated that is stored in `localstorage` as `courseShuffleSeed`, and based on that random value, the courses are shown, guaranteeing same order even after refreshing.
