### ISSUE TITLE
Rethink/correct workflow how to name courses.md

### ISSUE THREAD

**Issue by Mir1001** [UM-LPM/short-courses#8]
Currently, the name has a date and an acronym in the filename. The date in the name is used to sort courses. This problem will be if we automatically generate or modify MD files from different services.
- I suggest using an acronym for the course filename.
- Add field `version`, `date`, and `lastUpdate` in the files course.md, it will default to `1.1.2024`, `0.1.1` and `9.3.2024`. 
- Course order/sorting should be random.

- [Use this: reorder with refresh, I guess this can be used](https://thornelabs.net/posts/display-random-jekyll-posts-during-each-page-load-or-refresh-using-javascript/)
- [If it will be needed we can use: Snipped if order generated by compile, pro it is not confusing user](https://thornelabs.net/posts/a-better-way-to-display-random-jekyll-posts-on-page-load-or-refresh-using-jquery-and-json/)
- [Random](https://stackoverflow.com/questions/11397245/jekyll-randomly-sort-collection)

**Comment by cecepasinechka** [comment]
Fixed issue. 
- Renamed all courses files to just `ID.md`. 
- Adjusted `date` and added `lastUpdate` and `version`. 
- Added script to show random courses on refresh. 
- Properly adjusted `course-data.json` and `course-data-filtered.json` to include all data needed by the script. 
- Fixed **See also** to always display 3 other courses: first check all similar tags, then fill with other "random" courses.
