### ISSUE TITLE
Set actual houts instead of ECTS in display

### ISSUE THREAD

**Issue by Mir1001** [UM-LPM/short-courses#9]
From the number, generate the actual expected hour. For example, in the course file, we have 1 ECTS, from 1 generate actual hours 25-30 ur (1 ECTS) in the display table,  for example 2 ECTS generate 50-60 ur (2 ECTS) ... Remove * for ECTS from table

**Comment by cecepasinechka** [comment]
Ajdusted look. Set hours in the format `ECTS * 25` - `ECTS * 30`.
